[\#222 Issue](https://github.com/rear/rear/issues/222) `closed`: "Mount command failed" during recovery attempt - Ubuntu 10.04
==============================================================================================================================

**Labels**: `waiting for info`

#### <img src="https://avatars.githubusercontent.com/u/4115982?v=4" width="50">[TimDowker](https://github.com/TimDowker) opened issue at [2013-04-10 14:59](https://github.com/rear/rear/issues/222):

Trying to do a recovery to dis-similar hardware and keep getting "Mount
command failed" error.  I have confirmed the ext3 module is loaded and
I've tried re-running the backup just to be sure.  I'm running the
latest GIT - synced yesterday, with an external USB drive.  Any
thoughts?

Here's the output of my backup command - the format of the USB device
also gave no errors.

sudo usr/sbin/rear -v mkbackup  
Relax-and-Recover 1.14 / Git  
Using log file: /home/tdowker/rear/var/log/rear/rear-MiddleSrv2.log  
Creating disk layout  
Creating root filesystem layout  
WARNING: Could not determine network driver for 'bond0'. Please make  
WARNING: sure that it loads automatically (e.g. via udev) or add  
WARNING: it to MODULES\_LOAD in
/home/tdowker/rear/etc/rear/{local,site}.conf!  
TIP: To login as root via ssh you need to set up
/root/.ssh/authorized\_keys  
Copying files and directories  
/home/tdowker/rear/etc/rear/local.conf'
-&gt;/tmp/rear.QdaY97YhodaPrae/rootfs/etc/rear/local.conf'  
Copying binaries and libraries  
Copying kernel modules  
Creating initramfs  
Writing MBR to /dev/sdc  
Copying resulting files to usb location  
Encrypting disabled  
Creating tar archive
'/tmp/rear.QdaY97YhodaPrae/outputfs/rear/MiddleSrv2/20130409.1009/backup.tar.gz'  
Archived 150873 MiB \[avg 16548 KiB/sec\]OK  
Archived 150873 MiB in 9337 seconds \[avg 16546 KiB/sec\]﻿

#### <img src="https://avatars.githubusercontent.com/u/4115982?v=4" width="50">[TimDowker](https://github.com/TimDowker) commented at [2013-04-10 15:05](https://github.com/rear/rear/issues/222#issuecomment-16180079):

![error](https://f.cloud.github.com/assets/4115982/362743/1421ec94-a1f0-11e2-98c3-3c7dd00a2c93.jpg)  
Here's a picture of what I'm getting.

#### <img src="https://avatars.githubusercontent.com/u/101384?v=4" width="50">[schlomo](https://github.com/schlomo) commented at [2013-04-10 15:09](https://github.com/rear/rear/issues/222#issuecomment-16180315):

What is in /dev/disk? Are there any symlinks there? Do you see the USB
disk  
in /proc/partitions? What's in the logs?

On 10 April 2013 17:05, TimDowker <notifications@github.com> wrote:

> \[image:
> error\][https://f.cloud.github.com/assets/4115982/362743/1421ec94-a1f0-11e2-98c3-3c7dd00a2c93.jpg](https://f.cloud.github.com/assets/4115982/362743/1421ec94-a1f0-11e2-98c3-3c7dd00a2c93.jpg)  
> Here's a picture of what I'm getting.
>
> —  
> Reply to this email directly or view it on
> GitHubhttps://github.com/rear/rear/issues/222\#issuecomment-16180079  
> .

#### <img src="https://avatars.githubusercontent.com/u/4115982?v=4" width="50">[TimDowker](https://github.com/TimDowker) commented at [2013-04-10 15:14](https://github.com/rear/rear/issues/222#issuecomment-16180705):

/dev/disk does have the symlink to "by-label". Yes, I see the USB disk
in /proc/partitions. The network isn't operational so I can't copy the
log off however I've attached another screen shot of the last few lines
of the log.  
![error2](https://f.cloud.github.com/assets/4115982/362795/64eed5f0-a1f1-11e2-81c9-676a93c34efc.jpg)

#### <img src="https://avatars.githubusercontent.com/u/101384?v=4" width="50">[schlomo](https://github.com/schlomo) commented at [2013-04-10 15:35](https://github.com/rear/rear/issues/222#issuecomment-16182109):

Can you manually mount the disk? Is the ext3 filesystem available  
(/proc/filesystems) or a loadable module?

On 10 April 2013 17:14, TimDowker <notifications@github.com> wrote:

> /dev/disk does have the symlink to "by-label". Yes, I see the USB disk
> in  
> /proc/partitions. The network isn't operational so I can't copy the
> log off  
> however I've attached another screen shot of the last few lines of the
> log.  
> \[image:
> error2\][https://f.cloud.github.com/assets/4115982/362795/64eed5f0-a1f1-11e2-81c9-676a93c34efc.jpg](https://f.cloud.github.com/assets/4115982/362795/64eed5f0-a1f1-11e2-81c9-676a93c34efc.jpg)
>
> —  
> Reply to this email directly or view it on
> GitHubhttps://github.com/rear/rear/issues/222\#issuecomment-16180705  
> .

#### <img src="https://avatars.githubusercontent.com/u/4115982?v=4" width="50">[TimDowker](https://github.com/TimDowker) commented at [2013-04-10 15:38](https://github.com/rear/rear/issues/222#issuecomment-16182315):

No, I can't manually mount it - gives the same error of wrong FS type.
Command I used was "mount -t ext3 /dev/sdb1 /mnt/USB" (obviously I
created /mnt/USB first). The ext3 filesystem is list in
/proc/filesystems along with ext2 and ext4 and a bunch of other ones.

#### <img src="https://avatars.githubusercontent.com/u/101384?v=4" width="50">[schlomo](https://github.com/schlomo) commented at [2013-04-10 15:51](https://github.com/rear/rear/issues/222#issuecomment-16183120):

Pls. show us your /proc/partitions and the output of blkid

On 10 April 2013 17:38, TimDowker <notifications@github.com> wrote:

> No, I can't manually mount it - gives the same error of wrong FS
> type.  
> Command I used was "mount -t ext3 /dev/sdb1 /mnt/USB" (obviously I
> created  
> /mnt/USB first). The ext3 filesystem is list in /proc/filesystems
> along  
> with ext2 and ext4 and a bunch of other ones.
>
> —  
> Reply to this email directly or view it on
> GitHubhttps://github.com/rear/rear/issues/222\#issuecomment-16182315  
> .

#### <img src="https://avatars.githubusercontent.com/u/4115982?v=4" width="50">[TimDowker](https://github.com/TimDowker) commented at [2013-04-10 15:53](https://github.com/rear/rear/issues/222#issuecomment-16183257):

![Screenshot1](https://f.cloud.github.com/assets/4115982/363018/cc5a237a-a1f6-11e2-8182-69bda7a94665.png)  
As requested.

#### <img src="https://avatars.githubusercontent.com/u/101384?v=4" width="50">[schlomo](https://github.com/schlomo) commented at [2013-04-10 15:57](https://github.com/rear/rear/issues/222#issuecomment-16183456):

Hmm, not really sure what it is. Anything useful in dmesg?

On 10 April 2013 17:53, TimDowker <notifications@github.com> wrote:

> \[image:
> Screenshot1\][https://f.cloud.github.com/assets/4115982/363018/cc5a237a-a1f6-11e2-8182-69bda7a94665.png](https://f.cloud.github.com/assets/4115982/363018/cc5a237a-a1f6-11e2-8182-69bda7a94665.png)  
> As requested.
>
> —  
> Reply to this email directly or view it on
> GitHubhttps://github.com/rear/rear/issues/222\#issuecomment-16183257  
> .

#### <img src="https://avatars.githubusercontent.com/u/4115982?v=4" width="50">[TimDowker](https://github.com/TimDowker) commented at [2013-04-10 16:05](https://github.com/rear/rear/issues/222#issuecomment-16183969):

Nothing really of note in dmesg - also checked /var/log/messages just to
be sure and again, nothing jumps out. I should note that I am attempting
to restore within a Hyper-V VM. If that makes any difference.

#### <img src="https://avatars.githubusercontent.com/u/4115982?v=4" width="50">[TimDowker](https://github.com/TimDowker) commented at [2013-04-10 16:24](https://github.com/rear/rear/issues/222#issuecomment-16185200):

Damn, I was wrong - just noticed in /var/log/messages "JBD: IO error
reading journal superblock" and "Attempt to access beyond end of device"

Screenshot attached.  
![Screenshot2](https://f.cloud.github.com/assets/4115982/363157/2514ed16-a1fb-11e2-9455-875a63dd55c7.png)

#### <img src="https://avatars.githubusercontent.com/u/888633?u=cdaeb31efcc0048d3619651aa18dd4b76e636b21&v=4" width="50">[gdha](https://github.com/gdha) commented at [2013-04-11 11:54](https://github.com/rear/rear/issues/222#issuecomment-16230015):

Does this mean that your USB device is somehow broken?

#### <img src="https://avatars.githubusercontent.com/u/4115982?v=4" width="50">[TimDowker](https://github.com/TimDowker) commented at [2013-04-11 13:43](https://github.com/rear/rear/issues/222#issuecomment-16235015):

ghda - that's exactly what I suspected. Re-ran the backup last night and
I'm just testing out the recovery now. I'll update as soon as I find
out.

#### <img src="https://avatars.githubusercontent.com/u/4115982?v=4" width="50">[TimDowker](https://github.com/TimDowker) commented at [2013-04-11 14:01](https://github.com/rear/rear/issues/222#issuecomment-16236049):

Nope, same error - tried a completely different external USB drive. Any
other ideas?

#### <img src="https://avatars.githubusercontent.com/u/888633?u=cdaeb31efcc0048d3619651aa18dd4b76e636b21&v=4" width="50">[gdha](https://github.com/gdha) commented at [2013-04-12 12:29](https://github.com/rear/rear/issues/222#issuecomment-16290233):

do you see these errors during mkbackup too?

#### <img src="https://avatars.githubusercontent.com/u/888633?u=cdaeb31efcc0048d3619651aa18dd4b76e636b21&v=4" width="50">[gdha](https://github.com/gdha) commented at [2013-04-13 09:38](https://github.com/rear/rear/issues/222#issuecomment-16330345):

How did you format the USB device?

#### <img src="https://avatars.githubusercontent.com/u/888633?u=cdaeb31efcc0048d3619651aa18dd4b76e636b21&v=4" width="50">[gdha](https://github.com/gdha) commented at [2013-06-03 09:58](https://github.com/rear/rear/issues/222#issuecomment-18831742):

@TimDowker any progress made?

#### <img src="https://avatars.githubusercontent.com/u/888633?u=cdaeb31efcc0048d3619651aa18dd4b76e636b21&v=4" width="50">[gdha](https://github.com/gdha) commented at [2013-10-02 12:11](https://github.com/rear/rear/issues/222#issuecomment-25533429):

@TimDowker is it OK to close the issue? Or you do need some more
assistance? If no response received within a month I'll close it
automatically

#### <img src="https://avatars.githubusercontent.com/u/4115982?v=4" width="50">[TimDowker](https://github.com/TimDowker) commented at [2013-10-02 12:50](https://github.com/rear/rear/issues/222#issuecomment-25535462):

Go ahead and close.

#### <img src="https://avatars.githubusercontent.com/u/5246794?v=4" width="50">[astafyev](https://github.com/astafyev) commented at [2013-10-27 19:57](https://github.com/rear/rear/issues/222#issuecomment-27177706):

Have the same issue with 1.15. The problem is that ext3 module is not
loaded if udev is present. Despite the fact that ext3 module is present
in /etc/modules it's not loaded in 40-start-udev-or-load-modules.sh
because udev is present. But udev doesn't load ext3 either.

------------------------------------------------------------------------

\[Export of Github issue for
[rear/rear](https://github.com/rear/rear).\]
